"""Add FoodLog table with foreign key to User

Revision ID: 80ea0941cf8e
Revises: d83ffbf936fd
Create Date: 2025-01-09 17:54:57.269512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ea0941cf8e'
down_revision = 'd83ffbf936fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_item', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('log_date', sa.Date(), nullable=False))
        batch_op.drop_column('description')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('log_date')
        batch_op.drop_column('food_item')

    # ### end Alembic commands ###
