"""Added table for Meal Plans

Revision ID: be925561ff82
Revises: 80ea0941cf8e
Create Date: 2025-01-16 20:15:54.112976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be925561ff82'
down_revision = '80ea0941cf8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('meal_plan', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_plan')
    # ### end Alembic commands ###
